//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Диплом
{
    using System;
    using System.Collections.Generic;
    
    public partial class lectures
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int subject_id { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime end_time { get; set; }
        public Nullable<int> teacher_id { get; set; }
        public string auditorium_id { get; set; }
    
        public virtual auditoriums auditoriums { get; set; }
        public virtual subjects subjects { get; set; }
        public virtual teachers teachers { get; set; }
    }
}
