//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Диплом
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container1 : DbContext
    {
        public Model1Container1()
            : base("name=Model1Container1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<auditoriums> auditoriums { get; set; }
        public virtual DbSet<groups> groups { get; set; }
        public virtual DbSet<groupswithsubjects> groupswithsubjects { get; set; }
        public virtual DbSet<hours> hours { get; set; }
        public virtual DbSet<lectures> lectures { get; set; }
        public virtual DbSet<semesters> semesters { get; set; }
        public virtual DbSet<students> students { get; set; }
        public virtual DbSet<subjects> subjects { get; set; }
        public virtual DbSet<teachers> teachers { get; set; }
        public virtual DbSet<type_of_final_test> type_of_final_test { get; set; }
        public virtual DbSet<type_of_lesson> type_of_lesson { get; set; }
    }
}
