//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Диплом
{
    using System;
    using System.Collections.Generic;
    
    public partial class subjects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public subjects()
        {
            this.groupswithsubjects = new HashSet<groupswithsubjects>();
            this.lectures = new HashSet<lectures>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int hours { get; set; }
        public bool Need_special_auditorium { get; set; }
        public bool need_full_semester { get; set; }
        public string type_of_lesson { get; set; }
        public string type_of_final_test { get; set; }
        public string special_auditorium { get; set; }
    
        public virtual auditoriums auditoriums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<groupswithsubjects> groupswithsubjects { get; set; }
        public virtual hours hours1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lectures> lectures { get; set; }
        public virtual type_of_lesson type_of_lesson1 { get; set; }
        public virtual type_of_final_test type_of_final_test1 { get; set; }
    }
}
